version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      
  app-dev:
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./src:/api/src
      - ./pom.xml:/api/pom.xml
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run

networks:
  app-network:
